// <auto-generated />
using System;
using Ledgerly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledgerly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerlyDbContext))]
    [Migration("20260917155805_AddLedgerAccountPurpose")]
    partial class AddLedgerAccountPurpose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ledgerly.Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_wallets_id_currency");

                    b.HasIndex("OwnerId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_owner_id_currency");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_journal_entries_id_currency");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_ledger_accounts_id_currency");

                    b.HasIndex("Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_test_funding_currency")
                        .HasFilter("purpose = 2");

                    b.HasIndex("WalletId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_wallet_id")
                        .HasFilter("wallet_id IS NOT NULL");

                    b.HasIndex("WalletId", "Currency");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_purpose_type_wallet", "(purpose = 1 AND type = 2 AND wallet_id IS NOT NULL) OR (purpose = 2 AND type = 1 AND wallet_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.PostingRecord", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.HasKey("JournalEntryId", "Sequence")
                        .HasName("pk_postings");

                    b.HasIndex("AccountId", "Currency");

                    b.HasIndex("JournalEntryId", "Currency");

                    b.ToTable("postings", null, t =>
                        {
                            t.HasCheckConstraint("ck_postings_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_postings_direction", "direction IN (1, 2)");

                            t.HasCheckConstraint("ck_postings_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", b =>
                {
                    b.HasOne("Ledgerly.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_accounts_wallet_currency");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.PostingRecord", b =>
                {
                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_account_currency");

                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", null)
                        .WithMany("Postings")
                        .HasForeignKey("JournalEntryId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_journal_currency");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", b =>
                {
                    b.Navigation("Postings");
                });
#pragma warning restore 612, 618
        }
    }
}
