// <auto-generated />
using System;
using Ledgerly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledgerly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerlyDbContext))]
    partial class LedgerlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ledgerly.Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_wallets_id_currency");

                    b.HasIndex("OwnerId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_owner_id_currency");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_journal_entries_id_currency");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("ak_ledger_accounts_id_currency");

                    b.HasIndex("Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_test_funding_currency")
                        .HasFilter("purpose = 2");

                    b.HasIndex("WalletId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_wallet_id")
                        .HasFilter("wallet_id IS NOT NULL");

                    b.HasIndex("WalletId", "Currency");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_purpose_type_wallet", "(purpose = 1 AND type = 2 AND wallet_id IS NOT NULL) OR (purpose = 2 AND type = 1 AND wallet_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempt_count_non_negative", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.PostingRecord", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.HasKey("JournalEntryId", "Sequence")
                        .HasName("pk_postings");

                    b.HasIndex("AccountId", "Currency");

                    b.HasIndex("JournalEntryId", "Currency");

                    b.ToTable("postings", null, t =>
                        {
                            t.HasCheckConstraint("ck_postings_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_postings_direction", "direction IN (1, 2)");

                            t.HasCheckConstraint("ck_postings_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.TestDepositOperationRecord", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("balance");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.HasKey("WalletId", "Key")
                        .HasName("pk_test_deposit_operations");

                    b.HasIndex("JournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_test_deposit_operations_journal_entry_id");

                    b.ToTable("test_deposit_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_deposit_operations_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.WalletTransferRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DestinationBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("destination_balance");

                    b.Property<Guid>("DestinationWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_wallet_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<decimal>("SourceBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("source_balance");

                    b.Property<Guid>("SourceWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transfers");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("JournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_transfers_journal_entry_id");

                    b.HasIndex("SourceWalletId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_transfers_source_wallet_id_idempotency_key");

                    b.ToTable("wallet_transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_transfers_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", b =>
                {
                    b.HasOne("Ledgerly.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_accounts_wallet_currency");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.PostingRecord", b =>
                {
                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.LedgerAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_account_currency");

                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", null)
                        .WithMany("Postings")
                        .HasForeignKey("JournalEntryId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_journal_currency");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.TestDepositOperationRecord", b =>
                {
                    b.HasOne("Ledgerly.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_deposit_operations_wallet");

                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_deposit_operations_journal");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.WalletTransferRecord", b =>
                {
                    b.HasOne("Ledgerly.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transfers_destination_wallet");

                    b.HasOne("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transfers_journal");

                    b.HasOne("Ledgerly.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transfers_source_wallet");
                });

            modelBuilder.Entity("Ledgerly.Infrastructure.Persistence.Records.JournalEntryRecord", b =>
                {
                    b.Navigation("Postings");
                });
#pragma warning restore 612, 618
        }
    }
}
